<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/solicitante/inicio',
                'icono' => 'pi pi-check-circle',
                'rol' => 1, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificaciones',
                'url' => '/solicitante/notificacion',
                'icono' => 'pi pi-check-circle',
                'rol' => 1, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/solicitante/ver-tramite',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Nuevo',
                'tipo' => 'tramites',
                'url' => '/solicitante/nuevo-tramite',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis tramites',
                'tipo' => 'certificados',
                'url' => '/solicitante/ver-certificado',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Nuevo',
                'tipo' => 'certificados',
                'url' => '/solicitante/nuevo-certificado',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/solicitante/solicitudes-realizadas',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/solicitante/tramites-observados',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitados',
                'tipo' => 'reportes',
                'url' => '/solicitante/tramites-inhabilitados',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/solicitante/certificados-emitidos',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/solicitante/ayuda',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/operador/inicio',
                'icono' => 'pi pi-check-circle',
                'rol' => 3, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificaciones',
                'url' => '/operador/notificacion',
                'icono' => 'pi pi-check-circle',
                'rol' => 3, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/operador/ver-tramite',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Revisar Requisito',
                'tipo' => 'tramites',
                'url' => '/operador/revisar-requisito',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Elaborar Certificado',
                'tipo' => 'tramites',
                'url' => '/operador/elaborar-certificado',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Elaborar Informe',
                'tipo' => 'tramites',
                'url' => '/operador/elaborar-informe',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Todos los Certificados',
                'tipo' => 'certificados',
                'url' => '/operador/ver-certificados',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos',
                'tipo' => 'certificados',
                'url' => '/operador/requisitos',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Informe',
                'tipo' => 'certificados',
                'url' => '/operador/informe',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/operador/solicitudes-realizadas',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/operador/tramites-observados',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitados',
                'tipo' => 'reportes',
                'url' => '/operador/tramites-inhabilitados',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/operador/certificados-emitidos',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/operador/ayuda',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/admin/inicio',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Usuarios',
                'tipo' => 'administracion',
                'url' => '/admin/usuarios',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Roles',
                'tipo' => 'administracion',
                'url' => '/admin/roles',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Asignación Roles y Permisos',
                'tipo' => 'administracion',
                'url' => '/admin/roles-permisos',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Asignación Menú Permiso',
                'tipo' => 'administracion',
                'url' => '/admin/menu-permisos',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos Certificación',
                'tipo' => 'administracion',
                'url' => '/admin/requisito-certificacion',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Entidades Solicitantes',
                'tipo' => 'administracion',
                'url' => '/admin/entidad-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/admin/ver-tramites',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos',
                'tipo' => 'tramites',
                'url' => '/admin/requisitos',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificacion',
                'url' => '/admin/notificacion',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/admin/solicitud-realizada',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/admin/tramite-observado',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitado',
                'tipo' => 'reportes',
                'url' => '/admin/tramite-inhabilitado',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/admin/certificado-emitido',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Vencidos',
                'tipo' => 'reportes',
                'url' => '/admin/certificado-vencido',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Por Acreedor',
                'tipo' => 'reportes',
                'url' => '/admin/acreedor',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Por Moneda',
                'tipo' => 'reportes',
                'url' => '/admin/moneda',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/admin/ayuda',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/seguimiento/inicio',
                'icono' => 'pi pi-check-circle',
                'rol' => 4, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/seguimiento/ver-tramite',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificado',
                'tipo' => 'certificados',
                'url' => '/seguimiento/certificado',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos',
                'tipo' => 'certificados',
                'url' => '/seguimiento/requisito',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Informe',
                'tipo' => 'certificados',
                'url' => '/seguimiento/informe',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/seguimiento/solicitudes-realizadas',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/seguimiento/tramites-observados',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitados',
                'tipo' => 'reportes',
                'url' => '/seguimiento/tramites-inhabilitados',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/seguimiento/certificados-emitidos',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/seguimiento/ayuda',
                'icono' => 'pi pi-check-circle',
                'rol' => 4,
                'estado' => 1,
            ],
        ]);
    }
}
