<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('menus')->insert([
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/inicio-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificaciones',
                'url' => '/notificacion-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/ver-tramite-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Nuevo',
                'tipo' => 'tramites',
                'url' => '/nuevo-tramite-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis tramites',
                'tipo' => 'certificados',
                'url' => '/ver-certificado-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Nuevo',
                'tipo' => 'certificados',
                'url' => '/nuevo-certificado-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/solicitudes-realizadas-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/tramites-observados-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitados',
                'tipo' => 'reportes',
                'url' => '/tramites-inhabilitados-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/certificados-emitidos-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/ayuda-solicitante',
                'icono' => 'pi pi-check-circle',
                'rol' => 1,
                'estado' => 1,
            ],
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/inicio-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificaciones',
                'url' => '/notificacion-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3, 
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/ver-tramite-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Revisar Requisito',
                'tipo' => 'tramites',
                'url' => '/revisar-requisito-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Elaborar Certificado',
                'tipo' => 'tramites',
                'url' => '/elaborar-certificado-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Elaborar Informe',
                'tipo' => 'tramites',
                'url' => '/elaborar-informe-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Todos los Certificados',
                'tipo' => 'certificados',
                'url' => '/ver-certificados-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos',
                'tipo' => 'certificados',
                'url' => '/requisitos-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Informe',
                'tipo' => 'certificados',
                'url' => '/informe-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/solicitudes-realizadas-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/tramites-observados-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitados',
                'tipo' => 'reportes',
                'url' => '/tramites-inhabilitados-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/certificados-emitidos-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Ayuda',
                'tipo' => 'ayuda',
                'url' => '/ayuda-operador',
                'icono' => 'pi pi-check-circle',
                'rol' => 3,
                'estado' => 1,
            ],
            [
                'nombre' => 'Inicio',
                'tipo' => 'inicio',
                'url' => '/inicio-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Usuarios',
                'tipo' => 'administracion',
                'url' => '/usuarios-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Roles',
                'tipo' => 'administracion',
                'url' => '/roles-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos Certificación',
                'tipo' => 'administracion',
                'url' => '/requisito-certificacion-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Entidades Solicitantes',
                'tipo' => 'administracion',
                'url' => '/entidad-solicitante-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Mis Tramites',
                'tipo' => 'tramites',
                'url' => '/ver-tramites-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Requisitos',
                'tipo' => 'tramites',
                'url' => '/requisitos-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Notificaciones',
                'tipo' => 'notificacion',
                'url' => '/notificacion-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Solicitudes Realizadas',
                'tipo' => 'reportes',
                'url' => '/solicitud-realizada-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Observados',
                'tipo' => 'reportes',
                'url' => '/tramite-observado-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Tramites Inhabilitado',
                'tipo' => 'reportes',
                'url' => '/tramite-inhabilitado-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Emitidos',
                'tipo' => 'reportes',
                'url' => '/certificado-emitido-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Certificados Vencidos',
                'tipo' => 'reportes',
                'url' => '/certificado-vencido-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Por Acreedor',
                'tipo' => 'reportes',
                'url' => '/acreedor-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
            [
                'nombre' => 'Por Moneda',
                'tipo' => 'reportes',
                'url' => '/moneda-admin',
                'icono' => 'pi pi-check-circle',
                'rol' => 2,
                'estado' => 1,
            ],
        ]);
    }
}
