version: '3.9'
services:
  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: 'quay.io/soketi/soketi:0.17-16-alpine'
    ports:
      - '6001:6001'
      - '9601:9601'
    environment:
      - SOKETI_DEBUG=${SOKETI_DEBUG}

      - DEFAULT_APP_ID=${DEFAULT_APP_ID}
      - DEFAULT_APP_KEY=${DEFAULT_APP_KEY}
      - DEFAULT_APP_SECRET=${DEFAULT_APP_SECRET}
      
      - PUSHER_HOST=${PUSHER_HOST}
      - PUSHER_PORT=${PUSHER_PORT}
      - PUSHER_SCHEME=${PUSHER_SCHEME}
      - METRICS_SERVER_PORT=${METRICS_SERVER_PORT}
    networks:
      - soketi_network

networks:
  soketi_network:
    driver: bridge
